# VisionTrack Configuration

model:
  name: "yolov8n.pt"
  confidence_threshold: 0.5
  iou_threshold: 0.45
  device: "cpu"  # or "cuda" for GPU

tracking:
  max_age: 30
  min_hits: 3
  iou_threshold: 0.3

video:
  input_source: 0  # 0 for webcam, or path to video file
  output_path: "outputs/"
  fps: 30
  frame_skip: 0

ui:
  theme: "light"
  show_confidence: true
  show_labels: true
  line_thickness: 2
